# Generated by Django 3.1.3 on 2020-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10),
        ),
    ]
